/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizki RB
 */
public class OperasiDuaAngka extends javax.swing.JFrame {

    /**
     * Creates new form OperasiDuaAngka
     */
    public OperasiDuaAngka() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfSatu = new javax.swing.JTextField();
        txtOperator = new javax.swing.JLabel();
        tfDua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btPlus = new javax.swing.JButton();
        btMin = new javax.swing.JButton();
        btKali = new javax.swing.JButton();
        btBagi = new javax.swing.JButton();
        btClr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tfSatu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfSatu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSatuKeyTyped(evt);
            }
        });

        txtOperator.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtOperator.setText(" ");

        tfDua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDuaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("=");

        tfHasil.setEditable(false);
        tfHasil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfSatu)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btPlus.setText("+");
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlusActionPerformed(evt);
            }
        });
        jPanel2.add(btPlus);

        btMin.setText("-");
        btMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinActionPerformed(evt);
            }
        });
        jPanel2.add(btMin);

        btKali.setText("x");
        btKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKaliActionPerformed(evt);
            }
        });
        jPanel2.add(btKali);

        btBagi.setText(":");
        btBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBagiActionPerformed(evt);
            }
        });
        jPanel2.add(btBagi);

        btClr.setText("Clear");
        btClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClrActionPerformed(evt);
            }
        });
        jPanel2.add(btClr);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi [nama]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void numberFilter(java.awt.event.KeyEvent evt) {                                       
        char input = evt.getKeyChar();
        if (! ((Character.isDigit(input)||
                (input == KeyEvent.VK_BACK_SPACE)||
               (input == KeyEvent.VK_DELETE))))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Hanya Number!!");
            evt.consume();;        
        }
    }
    private void cekInputKosong() {
        if (tfSatu.getText().isEmpty() || tfDua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi terlebih dahulu");
        }
    }
    
    private void btPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlusActionPerformed
        cekInputKosong();
        int hasilnya = Integer.parseInt(tfSatu.getText()) + Integer.parseInt(tfDua.getText());
        tfHasil.setText(hasilnya+ "");
        txtOperator.setText("+");
    }//GEN-LAST:event_btPlusActionPerformed

    private void btMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinActionPerformed
        int hasilnya = Integer.parseInt(tfSatu.getText()) - Integer.parseInt(tfDua.getText());
        tfHasil.setText(hasilnya+ "");
        txtOperator.setText("-");
    }//GEN-LAST:event_btMinActionPerformed

    private void btKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKaliActionPerformed
        int hasilnya = Integer.parseInt(tfSatu.getText()) * Integer.parseInt(tfDua.getText());
        tfHasil.setText(hasilnya+ "");
        txtOperator.setText("x");
    }//GEN-LAST:event_btKaliActionPerformed

    private void btBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBagiActionPerformed
        double hasilnya = Double.parseDouble(tfSatu.getText()) / Double.parseDouble(tfDua.getText());
        tfHasil.setText(hasilnya+ "");
        txtOperator.setText(":");
    }//GEN-LAST:event_btBagiActionPerformed

    private void btClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClrActionPerformed
        tfHasil.setText("");
        tfSatu.setText("");
        tfDua.setText("");
        txtOperator.setText("");
        tfSatu.requestFocus();
    }//GEN-LAST:event_btClrActionPerformed

    private void tfSatuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSatuKeyTyped
        numberFilter(evt);
    }//GEN-LAST:event_tfSatuKeyTyped

    private void tfDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDuaKeyTyped
        numberFilter(evt);
    }//GEN-LAST:event_tfDuaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperasiDuaAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBagi;
    private javax.swing.JButton btClr;
    private javax.swing.JButton btKali;
    private javax.swing.JButton btMin;
    private javax.swing.JButton btPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfDua;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfSatu;
    private javax.swing.JLabel txtOperator;
    // End of variables declaration//GEN-END:variables
}
